Fix membership auto-enroll webhooks
gocodebox/lifterlms-rest pull request #329
Opened 2023-11-15 21:55 UTC by brianhogg

## Description

Currently there is a check to avoid the same webhook firing multiple times, but it's only checking the first argument or ID. For webhooks like the one that fires for the `enrollment.created` topic, there's two arguments: the student ID and the product ID (course or membership). Because of this, for an enrollment in a membership with one or more auto enrolled courses, only the webhook for the first course fires.

This PR changes the logic to look at the entire argument array when determining if there is a duplicate webhook. However from testing, it appears that the Action Scheduler will not allow a duplicate entry to be added anyway, so the check can likely be removed entirely.

Fixes https://github.com/gocodebox/lifterlms/issues/2568

## How has this been tested?

Automated tests, and manually [with the instructions on the ticket](https://github.com/gocodebox/lifterlms/issues/2568).

## Screenshots 

<img width="888" alt="Captura de pantalla 2023-11-15 a las 4 34 07 p  m" src="https://github.com/gocodebox/lifterlms-rest/assets/627497/86a6febe-a6f4-48f6-89d6-66de7fce94e8">
<img width="882" alt="Captura de pantalla 2023-11-15 a las 4 34 14 p  m" src="https://github.com/gocodebox/lifterlms-rest/assets/627497/ebac41fd-6e23-467d-848b-f99f781fa216">
<img width="884" alt="Captura de pantalla 2023-11-15 a las 4 34 21 p  m" src="https://github.com/gocodebox/lifterlms-rest/assets/627497/139e0f1c-bad2-4a7c-a79e-551843913f9f">
<img width="881" alt="Captura de pantalla 2023-11-15 a las 4 34 28 p  m" src="https://github.com/gocodebox/lifterlms-rest/assets/627497/cbb90b61-4586-4f8a-a35f-1683970009f1">

## Types of changes

Bug fix

## Checklist:
- [ ] This PR requires and contains at least one changelog file. 
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

2023-11-16 14:18 UTC, kimcoleman commented
@brianhogg thank you for this code we will run some tests.

Could you rebase this PR to dev branch?

2023-11-16 16:37 UTC, brianhogg commented
> @brianhogg thank you for this code we will run some tests.
> 
> Could you rebase this PR to dev branch?

@kimcoleman done! :)

2023-11-17 08:02 UTC, actuallyakash commented
hey @brianhogg 

Thanks for the code and the tests. Looks good. 👌 
Gonna close my PR in favour of this PR.

2023-11-17 11:07 UTC, brianhogg commented
@actuallyakash I've removed the `is_already_processed` check and an associated test that was only checking if that check was happening in `should_deliver`.

It was a bit of luck when I made `is_already_processed` return `false` to verify the one test would pass, then noticed the new `test_multiple_hooks_for_single_webhook_only_schedules_once` test was also still passing :)

2023-11-21 09:10 UTC, actuallyakash requested changes

2023-11-21 09:10 UTC, actuallyakash commented on includes/models/class-llms-rest-webhook.php
> -		$this->processed[] = $args;
Just need a docblock update for this.

2023-11-21 09:10 UTC, actuallyakash commented on includes/models/class-llms-rest-webhook.php
> -			&& ! $this->is_already_processed( $args ); // Not already processed.
docblock update needed.

2023-11-21 09:17 UTC, actuallyakash commented
Hey @brianhogg 

> @actuallyakash I've removed the `is_already_processed` check and an associated test that was only checking if that check was happening in `should_deliver`.

Cool, thanks. Just need to update some doc blocks.

> It was a bit of luck when I made `is_already_processed` return `false` to verify the one test would pass, then noticed the new `test_multiple_hooks_for_single_webhook_only_schedules_once` test was also still passing :)

oh, nice :D 

Just putting here for discussion, the `is_already_processed()` check was introduced due to this issue: https://github.com/gocodebox/lifterlms-rest/issues/210

However, the issue was due to the `pending_delivery` check which stopped the new webhooks from being delivered if the old ones were stuck. The `pending_delivery` check was removed and `is_already_processed` was introduced.

From the current PR, we now know that `is_already_processed` is not useful as "Action Scheduler does not seem to allow scheduling two actions with the same arguments and the same webhook ID".

2023-11-21 13:40 UTC, brianhogg commented on includes/models/class-llms-rest-webhook.php
> -		$this->processed[] = $args;
Done!

2023-11-21 13:40 UTC, brianhogg commented on includes/models/class-llms-rest-webhook.php
> -			&& ! $this->is_already_processed( $args ); // Not already processed.
Also done :)

2023-11-21 13:44 UTC, brianhogg commented
> Cool, thanks. Just need to update some doc blocks.
> 

Docblocks updated, let me know if there's anything else or the updates aren't clear :)

> Just putting here for discussion, the `is_already_processed()` check was introduced due to this issue: #210
> 
> However, the issue was due to the `pending_delivery` check which stopped the new webhooks from being delivered if the old ones were stuck. The `pending_delivery` check was removed and `is_already_processed` was introduced.
> 
> From the current PR, we now know that `is_already_processed` is not useful as "Action Scheduler does not seem to allow scheduling two actions with the same arguments and the same webhook ID".

Thanks for the background! It doesn't look like this change will cause a regression. There's also now a test to ensure multiple actions can be scheduled for the same webhook in the same request, but with different arguments.

2024-01-17 18:52 UTC, merged